### ISSUE TITLE
Invalid regular expression: /[z-a]/

### ISSUE THREAD

**Issue by Yaffle** [ljharb/regexp.escape#1]
```
new RegExp("[" + RegExp.escape("z-a") + "]")
```

**Comment by ljharb** [comment]
Why is this an issue with the library?

**Comment by ljharb** [comment]
The purpose of the function is to escape syntax characters - not to provide a string that would make valid character class when composed with other strings.

**Comment by Yaffle** [comment]
@ljharb , "-" is a syntax character, not?
So what are the use cases for `RegExp.escape` ?

**Comment by ljharb** [comment]
No, it's not. The current proposal does not escape hyphens.

The proposal is likely dead in this form, so this package will evolve considerably the next time it's brought before the committee. However, the current use cases are simply to escape user input, such that `new RegExp(RegExp.escape(foo)).test(foo)` is always true.

**Comment by Yaffle** [comment]
@ljharb , BUT if extend the current proposal with only one small character - "-", it will increase number of use cases, not?

**Comment by ljharb** [comment]
Sure, which is why it was one of the alternate proposals. But, it's not in the current one, and that's all I'm concerned with.

**Comment by Yaffle** [comment]
@ljharb , OK, I see now, that `RegExp.escape` will not help me anyway, sorry for the noise
